# #8. Promises

## Introducation to Async

- 자바스크립트의 **비동기성**

  : 순차적으로 처리되는 것이 아니라 한꺼번에 실행됨

```javascript
const hello = fetch("google.com")

console.log("something")
console.log(hello)

// something
// Promise {<rejected>: TypeError: Failed to fetch ...
```



- **Promise**

  : 비동기 작업이 맞이할 미래의 완료 또는 실패와 그 결과 값을 나타냄

```javascript
const promiseExample = new Promise((resolve, reject) => {
    
})

console.log(promiseExample) // Promise {<pending>}
// promise가 아직 pending 중(끝나지 않음을 뜻함)
// 자바스크립트는 promise가 끝나길 기다림
```

*promise resolve*

```javascript
const promiseExample = new Promise((resolve, reject) => {
    setTimeout(resolve, 3000, "ok!") 
})

console.log(promiseExample)

setInterval(console.log, 1000, promiseExample)

// Promise {<pending>}
// Promise {<pending>}
// Promise {<pending>}
// Promise {<fulfilled>: "ok!"}
// Promise {<fulfilled>: "ok!"}
// ....
```

promise의 핵심은 아직 모르는 value와 함께 작업할 수 있다는 것



- Using Promises (Then)

  :자바스크립트에 promise가 끝난 이후 명령을 전달하기 위해선 값을 돌려달라고 명령어(then)를 지시 해야함

```javascript
const promiseExample = new Promise((resolve, reject) => {
    setTimeout(resolve, 3000, "ok!") 
})

promiseExample.then(value => console.log(value)) 
// 3초 뒤 ok! 출력
```

*reject: promise의 문제가 생기면(reject) 문제를 catch하면 됨*

```javascript
const promiseExample = new Promise((resolve, reject) => {
    setTimeout(reject, 3000, "no!") 
})

promiseExample.then(value => console.log(value)) 
// 3초 뒤 error

promiseExample.then(result => console.log(result)).catch(error => console.log(error))
// 3초 뒤 no!

// promise가 resolve 되면 then이 실행되고 reject가 되면 catch가 실행됨
```

